### ISSUE TITLE
mesos-slave doesn't come up with the net-module enabled

### ISSUE THREAD

**Issue by oleksiys** [mesosphere/net-modules#74]
mesos-slave fails to start with the net-module enabled.
The error I find in log is [1], the glog lib is [2].

In general I'd say that installing net-module for mesos isn't easy and straight forward task at all. Is there any plan to include this module as part of standard mesos rpm? [3]

Thanks.

[1] mesos-slave[24488]: segfault at 7fle3ce0c828 ip 00007f1e34d44acc sp 00007ffc4484fdd0 error 7 in libglog.so.0.0.0 [7fle34d3b000+1e000]

[2] $ rpm -qf /usr/lib64/libglog.so.0.0.0
glog-0.3.3-8.el7.x86_64

[3] https://open.mesosphere.com/getting-started/install/

**Comment by spikecurtis** [comment]
Yeah, we're working on making this better.  Right now you have to build mesos-slave with glog "unbundled" (e.g. `--with-glog=` on `./configure`) so that the `net-modules` compiles with the same version of glog.

**Comment by djosborne** [comment]
@oleksiys Here's a guide for compiling netmodules that includes steps for unbundled glog: https://github.com/projectcalico/calico-docker/blob/master/docs/mesos/ManualInstallNetmodules.md
