### ISSUE TITLE
isolator/ipam command not found & net-modules remains disabled

### ISSUE THREAD

**Issue by unclejack** [mesosphere/net-modules#87]
PR #86 has broken net-modules. The ipam/isolator is not being picked up at all and it exists on the file system. Reverting PR #86 makes net-modules work again.

**Comment by djosborne** [comment]
@unclejack we've merged a fix. Your issue should be resolved

**Comment by unclejack** [comment]
@djosborne Thank you. I can confirm that it fixes the issue.
