### ISSUE TITLE
Net modules support for mesos-0.27.0

### ISSUE THREAD

**Issue by kuldeepsinh-3990** [mesosphere/net-modules#93]
With latest release of mesos , I tried to bind netmodules, but failed with compilation error.
Some changes of mesos-0.27.0 is not reflected in net-modules. Is netmodules yet to update with mesos-0.27.0 ? any roadmap for netmodules support with mesos-0.27.0?

**Comment by djosborne** [comment]
Yes, the [integration/0.27.0 branch](https://github.com/mesosphere/net-modules/tree/integration/0.27.0) should integrate with 0.27

**Comment by djosborne** [comment]
We've since merged the `integration/0.27` branch into master. So master builds should be compatible with 0.27
